### ISSUE TITLE
Prepare issue description to post on qibo

### ISSUE THREAD

**Issue by marekgluza** [csookim/qibo_transpiler_cskim#28]
Hi Changsoo,

can you post here a first version to the feature description that we are brainstorming in #27?
Then later we will move it to qibolab

This doesn't need to be complete in proposing the solution but:
- [ ] state the problem 
    - [ ] link the discussion that exist and are linked there
- [ ] summarize the proposed approach

Ping me when done to check again if individual sentences should be clarified or maybe we should first explain something about the qibolab workflow because it's new to you - this issue is meant to give space to onboarding you to the technicalities

**Comment by csookim** [comment]
Ok. After I document the results of the runtime comparison, I'll try to understand it.

**Comment by csookim** [comment]
# Components

- Qibolab: One of the Qibo backends. Interface of a real quantum hardware.
- Platform: The QPU configuration that contains information about instruments, gates, channels, etc.
- Runcard: A JSON file that stores information about a platform. It is loaded using `load_runcard()`.

# Problem

- There is no transpiler in Qibolab, which generates errors. [#927](https://github.com/qiboteam/qibolab/issues/927)
- A transpiler that considers gate and qubit properties is needed.
- The current method to call the transpiler is not user-friendly.

# Possible Solutions

## 1. Transpiler in Qibo

- A function is needed to initialize the transpiler based on the runcard file.
- The current transpiler pass requires connectivity and native gates as necessary information to transpile. More information, such as qubit and gate properties, needs to be considered.
- The custom transpiler is defined using Transpiler passes ([ref](https://qibo.science/qibo/stable/code-examples/advancedexamples.html#how-to-modify-the-transpiler)). 
- All backends will receive fully transpiled gates from Qibo (no need to transpile on the backend side).
- **For Simulation Backends**: Users should be able to use 1) no transpiler, 2) the default transpiler, or 3) a custom transpiler with a custom QPU (from a custom runcard file).
- **For Hardware Backends**: Users should be able to use a custom transpiler with a real QPU (from the runcard file).

## 2. Transpiler in Qibolab

- Specialized transpilers are needed for different backends.
- For most simulations, the circuit is not transpiled. To transpile the circuit, users can use a `Fakebackend`, which simulates transpiled circuits.
- The Qibolab transpiler uses all information based on the runcard file.
- **For Simulation Backends**: Users should be able to use 1) no transpiler, 2) the default transpiler, or 3) a custom transpiler with a custom runcard file using `Fakebackend`.
- **For Hardware Backends**: Users should be able to use a custom transpiler based on the information they wrote in the runcard file.

## 3. Transpiler in Qibo and Qibolab

- Keep the original Qibo transpiler and add an additional transpiler specialized for Qibolab.
- The Qibolab transpiler uses all information based on the runcard file.

**Comment by csookim** [comment]
@sorewachigauyo @marekgluza I added a summary and wrote some simple solutions. If there is anything I have misunderstood, please let me know.

**Comment by marekgluza** [comment]
Lgtm - let's see what core devs will say.

Please expect that the issue will be mentioned tomorrow in the meeting

Thanks!

**Comment by csookim** [comment]
@alecandido

**Comment by alecandido** [comment]
Just to state it explicitly, I'm in favor of 1. The detailed plan is coming in a Qibo issue.

2 is too convoluted, and we pushed the transpiler away from Qibolab because it was not specific to it.
Moreover, forget about the platform: this can be solved at the backend level (then we will expose some more attributes also in the `QibolabBackend` and they will be linked to the underlying platform - but this will remain Qibolab specific).

**Comment by alecandido** [comment]
It was already here https://github.com/qiboteam/qibo/issues/1309
