### ISSUE TITLE
Compare Shortestpath Router vs SABRE Router

### ISSUE THREAD

**Issue by csookim** [csookim/qibo_transpiler_cskim#4]
- [x] Check if the Shortestpath algorithm is worse than SABRE
- [x] 5-qubit star/cycle graphs.
- [x] Transpile QFT and random CNOT circuits.
- [x] Find and make a histogram about fluctuations.
- [x] Write a notebook file in test/transpiler_examples.

> Fluctuations come from equivalent swap move decisions in routing.

**Comment by marekgluza** [comment]
- [ ] is shortest path still better than Qiskit sabre?
