### ISSUE TITLE
Comparison with OLSQ

### ISSUE THREAD

**Issue by csookim** [csookim/qibo_transpiler_cskim#6]
- [x] Make a tutorial notebook comparing the Qibo router vs. OLSQ.
- [x] Create a directory with a markdown file collecting useful literature links.
- [ ] Use Arline Benchmarks. [github](https://github.com/ArlineQ/arline_benchmarks) [arxiv](https://arxiv.org/abs/2202.14025)

**Comment by marekgluza** [comment]
- [ ] check if optimal routing gives same transpiling as qiskit sabre or qiskit still better?
