### ISSUE TITLE
Create a 1Q Tutorial

### ISSUE THREAD

**Issue by csookim** [csookim/qibo_transpiler_cskim#9]
- [x] Create a tutorial for one qubit Qibo transpiler execution.

**Comment by marekgluza** [comment]
to send this to Paul please add him to this repo https://github.com/sorewachigauyo

**Comment by csookim** [comment]
I added him. Thanks!

**Comment by marekgluza** [comment]
@sorewachigauyo We could use this as an example to show @csookim the execution of circuits on qpu
